name: Build and deploy frontend to Azure Web App - cloud-task-manager-frontend-100397

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        env:
          VITE_API_URL: https://cloud-task-manager-api-100397-epb7cyf0grdcc2a0.swedencentral-01.azurewebsites.net/api
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3123C59A8EA447E1B2F0DCA93C5857AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0DD5646AFE89445988A4D97242A6C223 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6B1DAEA823545FB90509F8BB60F735B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cloud-task-manager-frontend-100397
          slot-name: Production
          package: .
